### PR TITLE
Support for Pimoroni build of 1.19 and Pico W

### LINKED ISSUE #13: Support for MicroPython 1.19 to include Pico W
https://github.com/ae5au/pico-solar-system

I've created a fork with support for the latest Pimoroni build of MicroPython 1.19 including the new PicoGraphics framework. It also supports the Pico W...eventually using ntp to sync time removing the need for an RTC if using somewhere that has Wi-Fi.

Please take a look and let me know if you have a chance to try it out. I have some more changes to make and would like some feedback before submitting a PR.

Requires installing v1.19 or later from Pimoroni:
https://github.com/pimoroni/pimoroni-pico/releases/

### PR DESCRIPTION
**Pull request by ae5au**
* Moved from PicoDisplay to PicoGraphics, Button, and RGBLED libraries to support newer Pimoroni MicroPython builds.
* Added support for Wi-Fi and NTP when using Pico W
* Updated README with Pico W instruction
* Added link to remix of case without RTC

Notes: NTP time will be in UTC.
Resolves #13

### CODE REVIEW

**Comment by ae5au** [comment]
@dr-mod: any thoughts on this?

**Comment by acyanic** [comment]
Well, you beat me by a month.
I've also just done an update to PicoGraphics - but sadly not with Pico W.
Your changes look good.
I had 2 other issues:
- dual button press
- epoch and Y2038
- 
I added a 1 year jump with button X (my backlight doesn't seem to respond):
I changed the logic (my preview for this is a mess first few lines in separate quotes):

```
if button_x.read():    # factor date change by 1 year
        if button_a.read():
            plusDays += 86400 * 365
            change = 3
        elif button_b.read():
            plusDays -= 86400 * 365
            change = 3
        backlight += 0.05
        if backlight > 1:
           backlight = 0.7
        display.set_backlight(backlight)
    elif button_y.read():  # cycle backlight
        backlight -= 0.05
        if backlight < 0:
            backlight = 1  # oo thats bright
        display.set_backlight(backlight)
    if button_a.read():
        if button_b.read():
           plusDays = 0
           change = 2
        else:
           plusDays += 86400
           change = 3
    elif button_b.read():
        plusDays -= 86400
        change = 3
```

Epoch and Y2038 error trap:

```
        if ticks_dif >= 1000 or time.time() != seconds_absolute:
            seconds_absolute = time.time()
            if plusDays > 2147483646 - seconds_absolute:
                plusDays = 2147483646 - seconds_absolute
            elif seconds_absolute + plusDays < 0:
                plusDays = seconds_absolute * -1
            ti = time.localtime(seconds_absolute + plusDays)
            start_int = time.ticks_ms()
            ticks_dif = 0
        if change > 0:
            if plusDays > 2147483646 - seconds_absolute:
                plusDays = 2147483646 - seconds_absolute
            elif seconds_absolute + plusDays < 0:
                plusDays = seconds_absolute * -1
            ti = time.localtime(seconds_absolute + plusDays)
```

I can add a pull request if Dmytro is still interested.

**Comment by ae5au** [comment]
Cool feature @acyanic! I will try it out.

Do you know if your RTC is the version Dmytro's original code supports or the version that I later added fallback code to support? If the latter, I think there are hardware conflicts between it and the Pico Display that prevents the LED and the brightness control from working properly. I know the LED problem is a shared pin with the i2c clock, but I never dug into why the brightness didn't work. 

Unfortunately, it isn't really clear when you purchase which version you are going to get. I ordered 2 from one vendor and then a third from a second vendor and received the same version on all 3 of them. Ironically, I think they are the older version and the original project was build on a newer version. Waveshare documentation isn't the best.

**Comment by acyanic** [comment]
Thanks, progressing a day at a time was a tad tedious.
RTC is Dmytro code as is, and no issue that I can see, apart from the brightness.  The LED works fine for me, although it's nasty bright!
I do have a set of mixed pixels along the top edge though, so that may be a conflict, but it doesn't affect the rest of the screen.

I'm looking at the epoch trap again, because negative time will regress further than that, to approx 1901.

fyi I also put some gaps between rocks and gas and gas and outers.

**Comment by ae5au** [comment]
> RTC is Dmytro code as is, and no issue that I can see, apart from the brightness. The LED works fine for me, although it's nasty bright!
> I do have a set of mixed pixels along the top edge though, so that may be a conflict, but it doesn't affect the rest of the screen.

I should have been more clear. My code was PRed into Dmytro's repo back in October of 2021...

https://github.com/dr-mod/pico-solar-system/commits/main/ds3231.py

**Comment by acyanic** [comment]
I only started on this this month, so it's as your commit.

Also, can you help with the date...

There's something odd in the date handling, that is not following Unix epoch 1970, nor the MicroPython epoch 2000 - or it's a mash up of the two!

Minimum date is 1932feb11, max date is 2068mar19 - which I guesss is microPython epoch, but these do not correspond to a full 32bit word, there's a roll over point

What i think is epoch:
```
>>> tt = time.localtime(0)
>>> print(tt)
(1970, 1, 1, 0, 0, 0, 3, 1)
```
Here's the roll over points:

```
>>> tt = time.localtime(-1,195,614,848)
>>> print(tt)
(1932, 2, 11, 20, 45, 52, 3, 42)

>>> tt = time.localtime(-1,195,614,849)
>>> print(tt)
(2068, 3, 19, 3, 14, 7, 0, 79)

```
and at 32 bit full:

```
>>> tt = time.localtime(2147483647)
>>> print(tt)
(2038, 1, 19, 3, 14, 7, 1, 19)

>>> tt = time.localtime(2147483648)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: overflow converting long int to machine word

>>> tt = time.localtime(-2,147,483,647)
>>> print(tt)
(2038, 1, 19, 3, 14, 9, 1, 19)
>>> 
```

**Comment by ae5au** [comment]
I've not worked much with date/time on MicroPython. When I was adapting the MicroPython NTP library for use on the RP2040 (it was written around the ESP8266), I had to change the NTP offset to account for a different epoch. Check the notes in this file:

https://github.com/ae5au/pico-solar-system/blob/main/ntptime.py

I'm sorry that probably isn't a lot of help, but it is all I have right now.

**Comment by acyanic** [comment]
It didn't help much :)
But I solved it with a timetravel cludge ...

```
        ticks_dif = time.ticks_diff(time.ticks_ms(), start_int)
        timetravel = 0
        if ticks_dif >= 1000 or time.time() != seconds_absolute:
            seconds_absolute = time.time()
            # micropython epoch 2000/1/1 unix epoch 1970/1/1
            # this is an abomination of both
            # time.localtime(0) is 1970 epoch
            # time.localtime( 2147483647) is (2038, 1, 19, 3, 14, 7, 1, 19)
            # time.localtime(- 2147483647) is (2038, 1, 19, 3, 14, 9, 1, 19)
            # time.localtime(- 1195614849) is (2068, 3, 19, 3, 14, 7, 0, 79)
            # time.localtime(- 1195614848) is (1932, 2, 11, 20, 45, 52, 3, 42)
            if plusDays > 2147483647 - seconds_absolute:
                timetravel =  - 2147483647 * 2 # switch to count up from negative
                if plusDays > (2147483647 * 2 - seconds_absolute - 1195614849):
                     plusDays = (2147483647 * 2 - seconds_absolute - 1195614849 - 60) # ceiling at 2068
            elif plusDays < (- 1195614848 - seconds_absolute): 
                plusDays = (- 1195614848 - seconds_absolute) # floor at 1938
            ti = time.localtime(seconds_absolute + plusDays + timetravel)
            start_int = time.ticks_ms()
            ticks_dif = 0
        if change > 0:
            if plusDays > 2147483647 - seconds_absolute:
                timetravel =  - 2147483647 * 2 # switch to count up from negative
                if plusDays > (2147483647 * 2 - seconds_absolute - 1195614849):
                     plusDays = (2147483647 * 2 - seconds_absolute - 1195614849 - 60) # ceiling at 2068
            elif plusDays < (- 1195614848 - seconds_absolute): 
                plusDays = (- 1195614848 - seconds_absolute) # floor at 1938
            ti = time.localtime(seconds_absolute + plusDays + timetravel)
```

**Comment by dr-mod** [comment]
Hi @ae5au Luke, great to see the changes you made to support Pico W, I cannot wait to merge it! Thanks! 
I was actually planning to clean up the project's code a little bit, but I'd rather do that after we merge you PR to avoid merge conflicts. I cannot verify the Pico W support just yet, but I bet you tested that part a dozen times already. 
I do have two questions:
1. I see that the color of the planets orbits have changed from grey to dark orange, is this what you see as well?
2. As for the create_pen function, I wonder if it's supposed to be called every time you need to get a color, you this is supposed to be stored in a variable / pallet. In other words, do you know if create_pen creates a new object every time that the GC has to clean up afterwards?

**Comment by ae5au** [comment]
1. I'm not sure. I'll test this hopefully this evening. I might have messed up one of the create_pen calls or the default mode of the display might be different. 

2. Based on the documentation, it just returns an integer (in the RGB mode we are using). I don't recall if I verified this, though. 

> In RGB565 and RGB332 modes this packs the given RGB into an integer representing a colour in these formats and returns the result.

https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/picographics/README.md#rgb565-rgb332-p8-and-p4-modes

**Comment by ae5au** [comment]
> I cannot verify the Pico W support just yet, but I bet you tested that part a dozen times already.

Yes, I've put a lot of time into testing the Pico W support and a few hours intro verifying Pico support. You have the newer version RTC and I have the older, so I would prefer if you make sure you don't have issues, too.

**Comment by acyanic** [comment]
Create_pen
I've seen examples that store result in variables, eg to set a set of
colours.
The examples are in the pimoroni repository.
In my bit of code of changes to yours,  I used pen_black as that was used a
few times in your code.
Andy

**Comment by ae5au** [comment]
@dr-mod ok, I flashed my Pico w/RTC back to your current version using 1.15 and compared to my Pico W running the latest commit (on my fork)...the colors are different. The planet orbit lines are the most obvious, but they are all slightly different. I'll test some different settings on PicoGraphic to see if I can get them to match.

**Comment by ae5au** [comment]
It was the mode. Default was 8-bit RGB332, and 16-bit RGB565 seems to perfectly match the old library.

https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/picographics/README.md#supported-graphics-modes-pen-type

I will test to make sure it didn't break anything on Pico w/RTC and then commit the change.

**Comment by ae5au** [comment]
Looks good to me on both Pico W and Pico w/RTC.

**Comment by dr-mod** [comment]
Thanks for the awesome addition Luke!

**Pull request merged**
